# Generated by Django 5.2.4 on 2025-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
    ]
