services:
  postgres:
    image: postgres:17.5-alpine
    container_name: urban_scope_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
        - ~/Documents/postgres-data:/var/lib/postgresql/data
