# Generated by Django 5.2.4 on 2025-08-02 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('basic_cnpj', models.CharField(unique=True)),
                ('company_name', models.CharField()),
                ('legal_nature', models.CharField()),
                ('qualification_of_the_person_in_charge', models.CharField()),
                ('share_company_capital', models.CharField()),
                ('company_size', models.CharField()),
                ('federal_entity_responsible', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_federal_revenue',
            },
        ),
    ]
