# Generated by Django 5.2.4 on 2025-08-02 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0002_alter_state_api_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('api_id', models.IntegerField()),
                ('name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state', to_field='api_id', db_column='state_id')),
            ],
            options={
                'db_table': 'municipality_ibge',
            },
        ),
    ]
