# Generated by Django 5.2.4 on 2025-08-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='integration_id',
            new_name='api_id',
        ),
    ]
