# Generated by Django 5.2.4 on 2025-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_rename_integration_id_municipality_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
    ]
